name = "aoc2019"
uuid = "1fa2abbd-f043-476b-805e-cba1faa86b72"
authors = ["AliothCancer <ortjuly7@gmail.com>"]
version = "0.1.0"

[deps]
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"

[compat]
Pipe = "1.3.0"
